export const clientsData = [
    {
        id: 1,
        companyName: 'Reliance Industries Ltd',
        contactPerson: 'Mukesh Ambani',
        email: 'tax@ril.com',
        phone: '+91 98200 12345',
        secondaryPhone: '+91 98200 54321',
        whatsapp: '+91 98200 12345',
        type: 'Company',
        pan: 'AAACA1234K',
        gstin: '27AAACA1234K1Z1',
        address: 'Maker Chambers IV, Nariman Point, Mumbai',
        services: ['GST Filing', 'Corporate Tax', 'TDS', 'Audit'],
        gstStatus: 'GST Paid & Confirmed',
        corpTaxStatus: 'Document Received',
        tdsStatus: 'GST Paid & Confirmed',
        itStatus: 'N/A',
        billing: { frequency: 'Monthly', method: 'Bank Transfer' },
        integrations: { salesforce: true, zoho: false, odoo: true },
        invoice: { total: 150000, paid: 150000, pending: 0, dueDays: 0 }
    },
    {
        id: 2,
        companyName: 'Sharma Textiles',
        contactPerson: 'Rajesh Sharma',
        email: 'rajesh@sharmatextiles.in',
        phone: '+91 91234 56789',
        secondaryPhone: '',
        whatsapp: '+91 91234 56789',
        type: 'Company',
        pan: 'BBBCB2345L',
        gstin: '27BBBCB2345L1Z2',
        address: 'Surat Textile Market, Surat, Gujarat',
        services: ['GST Filing', 'TDS'],
        gstStatus: 'Reminder Sent',
        corpTaxStatus: 'N/A',
        tdsStatus: 'Deadline Breached',
        itStatus: 'N/A',
        billing: { frequency: 'Quarterly', method: 'UPI' },
        integrations: { salesforce: false, zoho: true, odoo: false },
        invoice: { total: 45000, paid: 20000, pending: 25000, dueDays: 14 }
    },
    {
        id: 3,
        companyName: 'Dr. Anjali Desai',
        contactPerson: 'Anjali Desai',
        email: 'anjali.desai@clinic.com',
        phone: '+91 98765 43210',
        secondaryPhone: '',
        whatsapp: '+91 98765 43210',
        type: 'Individual',
        pan: 'CCCDC3456M',
        gstin: '27CCCDC3456M1Z3',
        address: 'Lilavati Hospital Rd, Bandra, Mumbai',
        services: ['Income Tax', 'GST Filing'],
        gstStatus: 'Document Requested',
        corpTaxStatus: 'N/A',
        tdsStatus: 'N/A',
        itStatus: 'Document Received',
        billing: { frequency: 'Annual', method: 'Cheque' },
        integrations: { salesforce: false, zoho: false, odoo: false },
        invoice: { total: 18000, paid: 18000, pending: 0, dueDays: 0 }
    },
    {
        id: 4,
        companyName: 'Tata Consultancy Services',
        contactPerson: 'N. Chandrasekaran',
        email: 'finance@tcs.com',
        phone: '+91 88888 88888',
        secondaryPhone: '',
        whatsapp: '+91 88888 88888',
        type: 'Company',
        pan: 'DDDCD4567N',
        gstin: '27DDDCD4567N1Z4',
        address: 'Banyan Park, Andheri, Mumbai',
        services: ['GST Filing', 'Corporate Tax', 'TDS', 'Audit', 'Advisory'],
        gstStatus: 'GST Paid & Confirmed',
        corpTaxStatus: 'GST Paid & Confirmed',
        tdsStatus: 'GST Paid & Confirmed',
        itStatus: 'N/A',
        billing: { frequency: 'Monthly', method: 'Bank Transfer' },
        integrations: { salesforce: true, zoho: true, odoo: true },
        invoice: { total: 500000, paid: 400000, pending: 100000, dueDays: 5 }
    },
    {
        id: 5,
        companyName: 'Gupta Logistics',
        contactPerson: 'Vikesh Gupta',
        email: 'vikesh@guptalogistics.com',
        phone: '+91 99999 11111',
        secondaryPhone: '',
        whatsapp: '+91 99999 11111',
        type: 'Company',
        pan: 'EEEEE5678O',
        gstin: '27EEEEE5678O1Z5',
        address: 'Nhava Sheva Port, Navi Mumbai',
        services: ['GST Filing', 'TDS'],
        gstStatus: 'Deadline Breached',
        corpTaxStatus: 'N/A',
        tdsStatus: 'Reminder Sent',
        itStatus: 'N/A',
        billing: { frequency: 'Quarterly', method: 'RazorPay Link' },
        integrations: { salesforce: false, zoho: false, odoo: false },
        invoice: { total: 30000, paid: 0, pending: 30000, dueDays: 32 }
    },
    {
        id: 6,
        companyName: 'Rahul Kapoor',
        contactPerson: 'Rahul Kapoor',
        email: 'rahul.k@freelance.in',
        phone: '+91 77777 22222',
        secondaryPhone: '',
        whatsapp: '+91 77777 22222',
        type: 'Individual',
        pan: 'FFFFF6789P',
        gstin: '27FFFFF6789P1Z6',
        address: 'Powai Hiranandani, Mumbai',
        services: ['Income Tax'],
        gstStatus: 'N/A',
        corpTaxStatus: 'N/A',
        tdsStatus: 'N/A',
        itStatus: 'Reminder Sent',
        billing: { frequency: 'Annual', method: 'UPI' },
        integrations: { salesforce: false, zoho: false, odoo: false },
        invoice: { total: 10000, paid: 0, pending: 10000, dueDays: 8 }
    },
    {
        id: 7,
        companyName: 'Patel Pharma',
        contactPerson: 'Sneha Patel',
        email: 'accounts@patelpharma.in',
        phone: '+91 66666 33333',
        secondaryPhone: '+91 66666 44444',
        whatsapp: '+91 66666 33333',
        type: 'Company',
        pan: 'GGGGG7890Q',
        gstin: '27GGGGG7890Q1Z7',
        address: 'GIDC, Ahmedabad, Gujarat',
        services: ['GST Filing', 'Corporate Tax', 'Audit'],
        gstStatus: 'Document Requested',
        corpTaxStatus: 'Document Requested',
        tdsStatus: 'N/A',
        itStatus: 'N/A',
        billing: { frequency: 'Monthly', method: 'Bank Transfer' },
        integrations: { salesforce: false, zoho: true, odoo: true },
        invoice: { total: 80000, paid: 80000, pending: 0, dueDays: 0 }
    },
    {
        id: 8,
        companyName: 'Mehta Jewelers',
        contactPerson: 'Karan Mehta',
        email: 'karan@mehtajewelers.com',
        phone: '+91 55555 44444',
        secondaryPhone: '',
        whatsapp: '+91 55555 44444',
        type: 'Company',
        pan: 'HHHHH8901R',
        gstin: '27HHHHH8901R1Z8',
        address: 'Zaveri Bazaar, Mumbai',
        services: ['GST Filing', 'Income Tax'],
        gstStatus: 'GST Paid & Confirmed',
        corpTaxStatus: 'N/A',
        tdsStatus: 'N/A',
        itStatus: 'GST Paid & Confirmed',
        billing: { frequency: 'Quarterly', method: 'Cheque' },
        integrations: { salesforce: false, zoho: false, odoo: false },
        invoice: { total: 60000, paid: 30000, pending: 30000, dueDays: 2 }
    },
    {
        id: 9,
        companyName: 'TechNova Solutions',
        contactPerson: 'Priya Singh',
        email: 'priya@technova.in',
        phone: '+91 44444 55555',
        secondaryPhone: '',
        whatsapp: '+91 44444 55555',
        type: 'Company',
        pan: 'IIIII9012S',
        gstin: '27IIIII9012S1Z9',
        address: 'IT Park, Pune',
        services: ['GST Filing', 'Corporate Tax', 'TDS'],
        gstStatus: 'Deadline Breached',
        corpTaxStatus: 'Reminder Sent',
        tdsStatus: 'Reminder Sent',
        itStatus: 'N/A',
        billing: { frequency: 'Monthly', method: 'RazorPay Link' },
        integrations: { salesforce: true, zoho: false, odoo: false },
        invoice: { total: 120000, paid: 0, pending: 120000, dueDays: 45 }
    },
    {
        id: 10,
        companyName: 'Ravi Verma',
        contactPerson: 'Ravi Verma',
        email: 'ravi.verma@art.com',
        phone: '+91 33333 66666',
        secondaryPhone: '',
        whatsapp: '+91 33333 66666',
        type: 'Individual',
        pan: 'JJJJJ0123T',
        gstin: '27JJJJJ0123T1Z0',
        address: 'Juhu, Mumbai',
        services: ['Income Tax'],
        gstStatus: 'N/A',
        corpTaxStatus: 'N/A',
        tdsStatus: 'N/A',
        itStatus: 'Document Requested',
        billing: { frequency: 'Annual', method: 'UPI' },
        integrations: { salesforce: false, zoho: false, odoo: false },
        invoice: { total: 15000, paid: 15000, pending: 0, dueDays: 0 }
    },
    {
        id: 11,
        companyName: 'Khan Enterprises',
        contactPerson: 'Imran Khan',
        email: 'imran@khanent.com',
        phone: '+91 22222 77777',
        secondaryPhone: '',
        whatsapp: '+91 22222 77777',
        type: 'Company',
        pan: 'KKKKK1234U',
        gstin: '27KKKKK1234U1Z1',
        address: 'Mohammed Ali Rd, Mumbai',
        services: ['GST Filing', 'Audit'],
        gstStatus: 'Document Received',
        corpTaxStatus: 'N/A',
        tdsStatus: 'N/A',
        itStatus: 'N/A',
        billing: { frequency: 'Half-Yearly', method: 'Bank Transfer' },
        integrations: { salesforce: false, zoho: true, odoo: false },
        invoice: { total: 70000, paid: 70000, pending: 0, dueDays: 0 }
    },
    {
        id: 12,
        companyName: 'Deshmukh Farms',
        contactPerson: 'Sanjay Deshmukh',
        email: 'sanjay@deshmukhfarms.in',
        phone: '+91 11111 88888',
        secondaryPhone: '',
        whatsapp: '+91 11111 88888',
        type: 'Company',
        pan: 'LLLLL2345V',
        gstin: '27LLLLL2345V1Z2',
        address: 'Nashik, Maharashtra',
        services: ['Income Tax', 'Advisory'],
        gstStatus: 'N/A',
        corpTaxStatus: 'N/A',
        tdsStatus: 'N/A',
        itStatus: 'GST Paid & Confirmed',
        billing: { frequency: 'Annual', method: 'Cheque' },
        integrations: { salesforce: false, zoho: false, odoo: false },
        invoice: { total: 25000, paid: 10000, pending: 15000, dueDays: 20 }
    }
];
