export const clientsData = [
    {
        id: 1,
        companyName: "Sharma Textiles Pvt Ltd",
        contactPerson: "Rajesh Sharma",
        email: "rajesh@sharmatextiles.in",
        phone: "+91 98765 43210",
        secondaryPhone: "+91 87654 32109",
        pan: "ABCDE1234F",
        gstin: "27ABCDE1234F1Z5",
        address: "124, MIDC Industrial Area, Andheri East, Mumbai",
        gstStatus: "GST Paid & Confirmed",
        corpTaxStatus: "Document Received",
        tdsStatus: "Reminder Sent",
        itStatus: "Document Requested",
        invoice: { total: 150000, paid: 150000, pending: 0, dueDays: 0 },
        services: ["GST Filing", "Corporate Tax", "TDS"],
        billing: { frequency: "Quarterly", entity: "JC Kabra & Associates", method: "Bank Transfer" },
        integrations: { zoho: true, salesforce: false, odoo: false }
    },
    {
        id: 2,
        companyName: "Mehta Electronics",
        contactPerson: "Priya Mehta",
        email: "priya@mehtaelectronics.com",
        phone: "+91 99887 76655",
        secondaryPhone: "",
        pan: "BCDEF2345G",
        gstin: "27BCDEF2345G1Z6",
        address: "Shop No 4, Lamington Road, Grant Road, Mumbai",
        gstStatus: "Deadline Breached",
        corpTaxStatus: "N/A",
        tdsStatus: "Document Requested",
        itStatus: "N/A",
        invoice: { total: 45000, paid: 15000, pending: 30000, dueDays: 14 },
        services: ["GST Filing", "TDS"],
        billing: { frequency: "Monthly", entity: "Kabra Tax Consultants LLP", method: "RazorPay Link" },
        integrations: { zoho: false, salesforce: false, odoo: false }
    },
    {
        id: 3,
        companyName: "Kapoor Constructions LLP",
        contactPerson: "Vikram Kapoor",
        email: "vikram@kapoorbuild.com",
        phone: "+91 91234 56789",
        secondaryPhone: "+91 99881 12233",
        pan: "CDEFG3456H",
        gstin: "27CDEFG3456H1Z7",
        address: "7th Floor, Builder House, Bandra Kurla Complex, Mumbai",
        gstStatus: "GST Paid & Confirmed",
        corpTaxStatus: "GST Paid & Confirmed",
        tdsStatus: "GST Paid & Confirmed",
        itStatus: "GST Paid & Confirmed",
        invoice: { total: 250000, paid: 250000, pending: 0, dueDays: 0 },
        services: ["GST Filing", "Corporate Tax", "TDS", "Income Tax", "Audit"],
        billing: { frequency: "Annual", entity: "JC Kabra & Associates", method: "Cheque" },
        integrations: { zoho: true, salesforce: true, odoo: false }
    },
    {
        id: 4,
        companyName: "Patel Pharma India",
        contactPerson: "Neha Patel",
        email: "neha.patel@patelpharma.in",
        phone: "+91 98230 11223",
        secondaryPhone: "",
        pan: "DEFGH4567I",
        gstin: "27DEFGH4567I1Z8",
        address: "Phase 2, Vapi Industrial Estate, Vapi",
        gstStatus: "Document Received",
        corpTaxStatus: "Document Requested",
        tdsStatus: "Reminder Sent",
        itStatus: "Reminder Sent",
        invoice: { total: 120000, paid: 0, pending: 120000, dueDays: 5 },
        services: ["GST Filing", "Corporate Tax", "TDS", "Income Tax"],
        billing: { frequency: "Quarterly", entity: "JC Kabra & Associates", method: "Bank Transfer" },
        integrations: { zoho: true, salesforce: false, odoo: false }
    },
    {
        id: 5,
        companyName: "Gupta Logistics",
        contactPerson: "Amit Gupta",
        email: "amit@guptalogistics.net",
        phone: "+91 97766 55443",
        secondaryPhone: "+91 91122 33445",
        pan: "EFGHI5678J",
        gstin: "27EFGHI5678J1Z9",
        address: "Transport Nagar, Mankhurd, Mumbai",
        gstStatus: "Review Pending",
        corpTaxStatus: "N/A",
        tdsStatus: "GST Paid & Confirmed",
        itStatus: "N/A",
        invoice: { total: 60000, paid: 40000, pending: 20000, dueDays: 32 },
        services: ["GST Filing", "TDS"],
        billing: { frequency: "Half-Yearly", entity: "Kabra Tax Consultants LLP", method: "Bank Transfer" },
        integrations: { zoho: false, salesforce: false, odoo: false }
    },
    {
        id: 6,
        companyName: "Reddy Agro Industries",
        contactPerson: "Srinivas Reddy",
        email: "srinivas@reddyagro.com",
        phone: "+91 99001 10099",
        secondaryPhone: "",
        pan: "FGHIJ6789K",
        gstin: "27FGHIJ6789K1Z0",
        address: "Navi Mumbai SEZ, Panvel",
        gstStatus: "Document Requested",
        corpTaxStatus: "Document Requested",
        tdsStatus: "Document Requested",
        itStatus: "Document Requested",
        invoice: { total: 85000, paid: 85000, pending: 0, dueDays: 0 },
        services: ["GST Filing", "Corporate Tax", "TDS", "Income Tax", "Advisory"],
        billing: { frequency: "Quarterly", entity: "JCKCA Advisory Services", method: "UPI" },
        integrations: { zoho: false, salesforce: false, odoo: false }
    },
    {
        id: 7,
        companyName: "Iyer & Sons Trading",
        contactPerson: "Lakshmi Iyer",
        email: "lakshmi@iyertrading.in",
        phone: "+91 88990 01122",
        secondaryPhone: "",
        pan: "GHIJK7890L",
        gstin: "27GHIJK7890L1Z1",
        address: "APMC Market, Vashi, Navi Mumbai",
        gstStatus: "Reminder Sent",
        corpTaxStatus: "N/A",
        tdsStatus: "N/A",
        itStatus: "Deadline Breached",
        invoice: { total: 15000, paid: 0, pending: 15000, dueDays: 45 },
        services: ["GST Filing", "Income Tax"],
        billing: { frequency: "Monthly", entity: "JC Kabra & Associates", method: "RazorPay Link" },
        integrations: { zoho: false, salesforce: false, odoo: false }
    },
    {
        id: 8,
        companyName: "Bajaj Auto Parts",
        contactPerson: "Suresh Bajaj",
        email: "suresh@bajajautoparts.co.in",
        phone: "+91 98111 22233",
        secondaryPhone: "",
        pan: "HIJKL8901M",
        gstin: "27HIJKL8901M1Z2",
        address: "Auto Nagar, Kurla West, Mumbai",
        gstStatus: "GST Paid & Confirmed",
        corpTaxStatus: "Document Received",
        tdsStatus: "Document Received",
        itStatus: "Document Received",
        invoice: { total: 105000, paid: 50000, pending: 55000, dueDays: 12 },
        services: ["GST Filing", "Corporate Tax", "TDS", "Income Tax"],
        billing: { frequency: "Quarterly", entity: "JC Kabra & Associates", method: "Bank Transfer" },
        integrations: { zoho: false, salesforce: true, odoo: false }
    },
    {
        id: 9,
        companyName: "Choudhary Steel Works",
        contactPerson: "Rahul Choudhary",
        email: "rahul@choudharysteel.com",
        phone: "+91 98222 33344",
        secondaryPhone: "+91 98333 44455",
        pan: "IJKLM9012N",
        gstin: "27IJKLM9012N1Z3",
        address: "Steel Yard, Mulund West, Mumbai",
        gstStatus: "GST Paid & Confirmed",
        corpTaxStatus: "GST Paid & Confirmed",
        tdsStatus: "GST Paid & Confirmed",
        itStatus: "GST Paid & Confirmed",
        invoice: { total: 200000, paid: 200000, pending: 0, dueDays: 0 },
        services: ["GST Filing", "Corporate Tax", "TDS", "Income Tax", "Audit"],
        billing: { frequency: "Annual", entity: "JC Kabra & Associates", method: "Cheque" },
        integrations: { zoho: false, odoo: true, salesforce: false }
    },
    {
        id: 10,
        companyName: "Nair Food Products",
        contactPerson: "Deepa Nair",
        email: "deepa@nairfoods.in",
        phone: "+91 97444 55566",
        secondaryPhone: "",
        pan: "JKLMN0123O",
        gstin: "27JKLMN0123O1Z4",
        address: "Food Park, Goregaon East, Mumbai",
        gstStatus: "Document Requested",
        corpTaxStatus: "N/A",
        tdsStatus: "Reminder Sent",
        itStatus: "N/A",
        invoice: { total: 40000, paid: 40000, pending: 0, dueDays: 0 },
        services: ["GST Filing", "TDS"],
        billing: { frequency: "Quarterly", entity: "Kabra Tax Consultants LLP", method: "UPI" },
        integrations: { zoho: false, salesforce: false, odoo: false }
    },
    {
        id: 11,
        companyName: "Joshi IT Solutions",
        contactPerson: "Manish Joshi",
        email: "manish@joshiit.com",
        phone: "+91 96555 66677",
        secondaryPhone: "",
        pan: "KLMNO1234P",
        gstin: "27KLMNO1234P1Z5",
        address: "Mindspace, Malad West, Mumbai",
        gstStatus: "Document Received",
        corpTaxStatus: "Document Received",
        tdsStatus: "GST Paid & Confirmed",
        itStatus: "Document Received",
        invoice: { total: 180000, paid: 100000, pending: 80000, dueDays: 2 },
        services: ["GST Filing", "Corporate Tax", "TDS", "Income Tax", "Advisory"],
        billing: { frequency: "Half-Yearly", entity: "JCKCA Advisory Services", method: "Bank Transfer" },
        integrations: { zoho: true, salesforce: false, odoo: false }
    },
    {
        id: 12,
        companyName: "Malhotra Jewellers",
        contactPerson: "Sunita Malhotra",
        email: "sunita@malhotrajewellers.in",
        phone: "+91 95666 77788",
        secondaryPhone: "+91 94777 88899",
        pan: "LMNOP2345Q",
        gstin: "27LMNOP2345Q1Z6",
        address: "Zaveri Bazaar, Kalbadevi, Mumbai",
        gstStatus: "Deadline Breached",
        corpTaxStatus: "Deadline Breached",
        tdsStatus: "Deadline Breached",
        itStatus: "Deadline Breached",
        invoice: { total: 130000, paid: 0, pending: 130000, dueDays: 18 },
        services: ["GST Filing", "Corporate Tax", "TDS", "Income Tax"],
        billing: { frequency: "Monthly", entity: "JC Kabra & Associates", method: "Bank Transfer" },
        integrations: { zoho: false, salesforce: false, odoo: false }
    }
];
